[package]
name = "grrs"
version = "0.1.0"
authors = ["holdlg <holdlg@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
indicatif = "0.14.0"